### ISSUE TITLE
[Refactor] Clean Architecture 적용

### ISSUE THREAD

**Issue by wjchoi96** [wjchoi96/KakaoGallery#1]
## 📚 To-do

- [x] Data, Domain, Presentation 패키지 분리
- [x] DataSource 추가
- [x] Repository 추상화. 각 모듈간 인터페이스 타입에 의존하도록 변경
- [x] 의존성 관리(Dagger Hilts)
- [x] UseCase 추가
- [x] Data, Domain 에러 처리 변경
