### ISSUE TITLE
[Refactor] UseCase패턴 적용

### ISSUE THREAD

**Issue by wjchoi96** [wjchoi96/KakaoGallery#10]
### UseCase패턴 적용
- #1 

## 📚 To-do

- [x] SearhUsecase를 추가하여 ViewModel에서 비즈니스 로직 제거
- [x] SearchUsecase를 통해 Repository와 ViewModel의 분리
- [x] SaveImage 관련 코드는 유지. 기능복구, 수정이 필요함

**Comment by wjchoi96** [comment]
**UseCase란?**
---

- 만들고 있는 서비스를 사용하는 유저가 이 서비스(또는 시스템)을 통해 하고자 하는 것
    - 즉, 최소 요청 단위
- 이미지 검색, 저장 서비스라면 아래와 같은 Usecase들이 존재하게 될 것
    - 이미지 검색
    - 이미지 저장
    - 저장된 이미지 목록
    - 이미지 삭제

**UseCase 사용의 장점**
---

`Android Architecture`에서는 **UseCase**를 재사용성 측면에서 강조를 하며 재사용성이 요구되지 않는다면 구현하지 않을것을 권장

하지만 `Clean Architecture` 관점에서 **UseCase**는 단순히 재사용성만을 강조하는것이 아닌 두가지 측면을 추가로 강조하며 도입을 권장

- **ViewModel**에서의 비즈니스 로직 분리
- **Repository**의 변경에서 **ViewModel**의 안전함

실제로 사용을 해본 결과, 재사용성 측면이 아니더라도 **UseCase패턴**은 도입할 가치가 충분했다고 생각됨

- **MVVM** 특성상 **ViewModel**이 비대해진다는 문제점이 있었는데(물론, **MVP**에서도 **Presenter**가 비대해지는 등 고질적인 문제로 보인다) **UseCase**로 비즈니스 로직을 이동하게 된 결과 **ViewModel**은 순수하게 **UI**의 **상태 홀더**로써의 역할을 수행할 수 있게 된다는 이점
- 현재 **UI**에서 사용되지 않는 **Repository**의 메소드들을 쓸데없이 노출하지 않게된다는 이점
- 재사용성 또한 우수함

이러한 경험을 할 수 있었으며, 앞으로도 **UseCase패턴**은 꼭 적용하게 될 것 같음
