### ISSUE TITLE
[Refactor] Data, Domain 에러 처리 변경

### ISSUE THREAD

**Issue by wjchoi96** [wjchoi96/KakaoGallery#12]
### Data, Domain 에러 처리 변경
 - #1 
## 📚 To-do

- [x] KakaoGallery 프로젝트에서 사용될 Custom Exception들을 DomainException.kt에 작성
- [x] DataSource는 데이터 원형을 리턴
- [x] Repository에서 Observable을 병합할때 하나의 스트림만 에러가 날 경우, 정상처리 되도록 처리(Image, Video 둘 중 하나만 에러가 발생한다면 정상 처리해야 함)
- [x] Repository는 데이터 원형을 리턴
- [x] UseCase에서 Error를 catch하여 적절한 래퍼클래스로 래핑하여 데이터 리턴
- [x] Presentation에서는 래퍼클래스를 통해 성공, 실패를 구분
- [x] 기존 Result클래스 제거

**Comment by wjchoi96** [comment]
**io.reactivex.rxjava3.exceptions.CompositeException**
---
- **하나 이상의 다른 예외가 복합된 예외**
    
    ```java
    public CompositeException(@NonNull Throwable... exceptions) {
    		this(exceptions == null ?
            Collections.singletonList(new NullPointerException("exceptions was null")) : Arrays.asList(exceptions));
    }
    
    public CompositeException(@NonNull Iterable<? extends Throwable> errors) {
        Set<Throwable> deDupedExceptions = new LinkedHashSet<>();
        if (errors != null) {
            for (Throwable ex : errors) {
                if (ex instanceof CompositeException) {
                    deDupedExceptions.addAll(((CompositeException) ex).getExceptions());
                } else
                if (ex != null) {
                    deDupedExceptions.add(ex);
                } else {
                    deDupedExceptions.add(new NullPointerException("Throwable was null!"));
                }
            }
        } else {
            deDupedExceptions.add(new NullPointerException("errors was null"));
        }
        if (deDupedExceptions.isEmpty()) {
            throw new IllegalArgumentException("errors is empty");
        }
        List<Throwable> localExceptions = new ArrayList<>(deDupedExceptions);
        this.exceptions = Collections.unmodifiableList(localExceptions);
        this.message = exceptions.size() + " exceptions occurred. ";
    }
    
    ```
    
    1. 전달된 **Throwable**들이 없다면 **NullPointerException**를 생성
    2.  전달된 **Throwable**을 **Set**에 저장(중복 허용되지 않음)
- **Stream**에서 에러가 여러번 발생(**throw**)하게 될 경우 발생한 에러들이 **CompositeException**로 래핑되어 전달됨
**CompositeException**은 에러를 래핑할때 내부적으로 **Set**을 사용하기 때문에 중복된 에러는 하나로 처리
- **Stream**에서 에러를 **throw**하는 방식으로 에러를 전달한다면 **CompositeException**내부의 에러를 확인하는 작업이 추가적으로 필요
    -  **Stream**을 진행하며 여러 에러가 발생(**throw**)될 가능성이 존재하기 때문
    - 에러 발생시 **onErrorResumeNext** 을 사용하여 새로운 스트림으로 대체한다면 **CompositeException**로 래핑하지 않고 에러를 전달 가능

[Preventing RxJava from wrapping my custom exception into composite one](https://stackoverflow.com/questions/57875237/preventing-rxjava-from-wrapping-my-custom-exception-into-composite-one)
[[CompositeException (RxJava Javadoc 3.1.5)](http://reactivex.io/RxJava/3.x/javadoc/io/reactivex/rxjava3/exceptions/CompositeException.html)

**Comment by wjchoi96** [comment]
**에러가 발생하면 onError로 보내면 되지 않을까?**
---
- **onError**이벤트는 **Stream**을 중단시키므로, `subscribe()`함수를 호출할때  **onError**이벤트를 직접 처리하는것은 `OOM`같은 중대한 에러가 발생했을때만 사용
- **onErrorReturn**을 사용하여 에러를 데이터로 변환
    - **onErrorReturnItem**은 **onErrorReturn**과 동일하지만, 전달인자로 **throwable**을 제공하지 않음
- **onErrorResumeNext**를 사용하여 에러를 새로운 스트림(**Observable**)으로 변환
    - 에러 발생 시 데이터를 교체하는 것뿐만 아니라 관리자에게 이메일을 보낸다던가 자원을 해제하는 등의 추가 작업을 해야할 때 유용
