### ISSUE TITLE
[Docs] android ci task 수정

### ISSUE THREAD

**Issue by wjchoi96** [wjchoi96/KakaoGallery#123]
## 📚 To-do

- [x]  build task에서 test를 수행하지 않도록 제거
    - `./gradlew build -x test`
- [x]  test task 추가
- [x]  어느 branch건 PR생성시 ci작동하도록 수정
