### ISSUE TITLE
#141 [Refactor] Clean Architecture에 걸맞지 않은 패키지 구조 리팩토링

### ISSUE THREAD

**Issue by wjchoi96** [wjchoi96/KakaoGallery#141]
## 📚 To-do

- [x]  `persentation.network` 패키지를 `data layer`로 이동
- [x]  `KakaoGallerySharedPreferences` 를 `data.local` 패키지로 이동
- [x]  ReadMe Package 수정

## 🕐 목표 작업 시간

2023.01.12 01:50 ~ 02:00
## 📆 실제 작업 시간

2023.01.12 01:50 ~ 01:55

**Comment by wjchoi96** [comment]
- **Android**에 **Clean Architecture**를 적용하면 **`Presentation Layer`** 에는 **Framework**인 **Android SDK**, **Persenter**인 **ViewModel**가 존재해야 하며 **`Data Layer`** 에는 **DB**, **API**의 코드가 존재해야 함
- 때문에 **Application**, **di**, **ui**, **viewModel**은 **Presentation**에 위치하고, **network**, **db**관련 코드는 **Data**에 위치하게 됨
