### ISSUE TITLE
[Rename] Coding convention 점검

### ISSUE THREAD

**Issue by wjchoi96** [wjchoi96/KakaoGallery#17]
### Code convention 점검
 - [Coding convention docs](https://github.com/wjchoi96/KakaoGallery/wiki/Coding-Convention)
## 📚 To-do

- [x] viewDataBinding의 약자인 vd를 binding으로 네이밍 변경
- [x] coding convention 문서를 기준으로 프로젝트 점검
- [x] ArrayList -> mutableList 처럼 좀 더 kotlin스러운 코드로 수정
