### ISSUE TITLE
[Feature] 이미지 선택, 저장 기능 구현

### ISSUE THREAD

**Issue by wjchoi96** [wjchoi96/KakaoGallery#21]
## 📚 To-do

- [x] [Modify]Toolbar 구현 방식 변경
- [x] [Refactor] SearchImage Muti View Type RecyclerView 구현 수정
- [x] [Feature]이미지 선택, 저장 기능 구현
