### ISSUE TITLE
[Modify] Toolbar 구현 방식 변경

### ISSUE THREAD

**Issue by wjchoi96** [wjchoi96/KakaoGallery#22]
### Toolbar 구현 방식 변경
- #21 

## 📚 To-do

- [x] HeaderComp를 제거
- [x] toolbar_header.xml 작성
- [x] Activity는 NoActionBar로 설정
- [x] item_toolbar_header.xml를 include 하여 각 Fragment에서 각각의 Toolbar를 설정
