### ISSUE TITLE
[Refactor] Search, Save 화면의 List 구현 방식 변경

### ISSUE THREAD

**Issue by wjchoi96** [wjchoi96/KakaoGallery#25]
### [Refactor] Search, Save 화면의 List 구현 방식 변경
- #21 

## 📚 To-do

- [x] SearchImage Muti View Type RecyclerView 구현 수정
- [x] Search 화면의 List를 DiffUtil + payload + DataBinding를 사용하여 Adapter 구현
- [x] Save 화면의 List를 DiffUtil + payload + DataBinding를 사용하여 Adapter 구현
