### ISSUE TITLE
[Fix] 선택모드, 이미지 저장 기능 복구

### ISSUE THREAD

**Issue by wjchoi96** [wjchoi96/KakaoGallery#27]
### 선택모드, 이미지 저장 기능 복구
- #21 
- 기존에 리팩토링 도중 중단
- 새롭게 리팩토링을 하며 일부 구현 방식이 변경됨으로 인해 작동이 안되는 기능이 존재

## 📚 To-do

- [x] Search Image 화면 선택모드 복구
- [x] Gallery 화면 선택모드 복구
- [x] Search Image 화면 이미지 저장 기능 복구
- [x] Gallery 화면 저장된 이미지 Fetch 기능 복구(Hot Stream을 통해 변경되는 데이터를 지속적으로 전달받음)
- [x] Gallery 화면 저장된 이미지 Remove 기능 복구
