### ISSUE TITLE
[Refactor] Dialog to FragmentDialog

### ISSUE THREAD

**Issue by wjchoi96** [wjchoi96/KakaoGallery#28]
## 📚 To-do

- [x] 기존 Dialog를 FragmentDialog로 변경
- [x] 상태 관리, 상태 보존, 관심사 분리를 위한 ViewModel 추가
- [x] Dialog에 DataBinding 적용

**Comment by wjchoi96** [comment]
**ViewModel을 사용한 상태 저장 vs ViewModel + SaveStateHandle를 사용한 상태 저장**
---

- **ViewModel**은 메모리에 위치하므로 프로세스가 종료되는 경우에는 **ViewModel**이 새롭게 생성됨
따라서, 운영체제에 의해 프로세스가 강제로 종료된 경우 상태저장을 수행할 수 없음
- **SaveInstanceState**는 디스크에 직렬화되어 저장되므로 위의 경우에도 상태저장을 수행 가능
- 프로세스가 강제로 종료되어도 상태 저장이 수행되어야 할 데이터가 있다면 
**ViewModel**의 **SaveStateHandle**의 사용을 고려해볼 수 있음

**SaveStateHandle를 사용했을때 장단점**
---

- 운영체제에 의해 프로세스가 강제로 종료당했을때 상태 저장
- **Activity**, **Fragment** 등 **UI**에서 **Extra** **Data**처리 코드를 **ViewModel**에서 처리 가능
- 어떠한 상태를 캐싱했다가 화면을 벗어날때 **DB**, 서버등에 일괄적용하는 로직등이 유실될 가능성을 줄여줌
- **Android**패키지의 코드가 **ViewModel**에 포함될 경우 **VIewModel** **Unit** **Test**가 우려됨

**KakaoGallery 프로젝트**
---

- 프로세스에 의해 강제로 종료되었다가 앱이 복원되는 경우 **Fragment**상태도 복원하기 때문에 **BottomSheet**가 펼처진 상태였다면 같이 복원됨
이때, 검색 결과, 선택된 이미지, **BottomSheet** **state** 정보들이 손실되어있다면 무척 어색한 상황일 것
- **ImageManageBottomSheetViewModel**
    - **bundle**을 통해 전달받는 **BottomSheet** 구성 요소 **set**, **get** 코드를 **ViewModel**에 작성해볼 예정
    - **content**, **listener** 정보 복구
- **RootViewModel**
    - **select current page** 복구
- **SearchImageViewModel**
    - **검색 query,** **select image**, **scroll** 위치 복구
    - 이미지 검색 결과는 **SaveStateHandle**에 저장하기엔 긴(길어질 수 있는) 데이터라고 생각되지만, 
    선택된 이미지 **map**과 검색 결과 **List**의 **idx sync**가 맞아야 하기에 같이 저장 시도
    - 이미지 검색 결과는 **LiveData** 형태로 저장

**Comment by wjchoi96** [comment]
**Fragment에서 lifeCycleOwner를 썼을때 발생할 수 있는 문제점**
---

- 기기 회전등의 이벤트가 발생했을때 화면(**ui**)는 재구성되는데 이때 **Activity**와 **Fragment**의 **lifeCycle** 불일치가 발생할 수 있음
- **Fragment**는 **this**(**fragment lifeCycleOwner**), **viewLifeCycleOwner** 총 2가지의 **lifeCycleOwner**를 가짐
- **기기 회전시**
    1. 기기 회전 이벤트 발생
    2. **Activity**는 `onDestory()`가 호출되며 `DESTORYED` **상태가 됨**
    **Fragment**는 `onDestoryView(`), `onDetach()`가 호출되며, `DESTORYED`**상태가 되지 않고** `STOPED`**상태가 됨**
    3. **Activity**는 `onCreate(Bundle)`이 호출되며 `CREATED` 상태가 됨
    **Fragment**는 `onAttach()`, `onCreateView(Bundle)`이 호출되며 `CREATED`상태가 됨
    - **Activity**는 `DESTROYED` → `CREATED` 상태가 되었지만 
    **Fragment**는 `STOPED` → `CREATED`가 되기때문에 옵저빙이 중복되거나, **DataBinding**이 올바르게 되지 않을 수 있음

**Fragment View Lifecycle은 위의 문제가 발생하지 않는 이유**
---

- **Fragment View Lifecycle**는 `onDestoryView()`가 호출되면 **DESTORYED**상태가 되기 때문에, 위의 불일치가 발생하지 않음
    - **Activity**는 `DESTROYED` → `CREATED` 상태가 될때 
    **Fragment View**도 `DESTROYED` → `CREATED`가 됨
- **Fragment**는 **Fragment View**보다 긴 생명주기를 가지며, 일반적으로 **UI**를 업데이트용으로는 **Fragment View Lifecycle**이 적절
    - **Fragment Lifecycle : Create ~ Destroy**
    - **Fragment View Lifecycle : createView ~ destoryView**
- **Fragment** 사용 시 데이터 갱신에 대한 **Lifecycle을 Fragment Lifecycle**보다 **Fragment View Lifecycle**이 올바르다고 권장

**DataBinding 사용시 언제 viewLifeCycleOwner로 적용해줘야 할까**
---

- **Fragment 1.2.0부터 새로운 Lint가 추가**
    - `onCreateView()`, `onViewCreated()`, `onActivityCreated()`에서 **LiveData** 사용 시에는 **ViewLifecycleOwner**를 사용하도록 권장
- **Fragment**가 `CREATED` 상태일때 진행하면 되는것으로 이해됨
