### ISSUE TITLE
[Refactor] Data Entity와 Domain Model 분리

### ISSUE THREAD

**Issue by wjchoi96** [wjchoi96/KakaoGallery#4]
### Data Entity와 Domain Model 분리
- #1 

## 📚 To-do

- [x] Data Entity와 Domain Model 분리
- [x] Data Entity가 Dto 역할도 수행하도록 관련 메소드 추가
- [x] Dto기능에 필요한 DateFormatter 추가

**Comment by wjchoi96** [comment]
**Data의 Entity**
---

- **Data**그 자체인 **Entity**
- **DB**테이블, **Api** 응답 형태와 매핑되는 클래스
    - **Server**, **DB**에서 불러오는 데이터의 형태
    - 이를 파싱하기 위한 의존성이 추가될 수 있음(**Room**, **Retrofit** 등)

**Domain의 Model**
---

- 클린 아키텍처 측면으로 바라보았을때 순수 **Java**/**Kotiln** 코드로 작성되어서 다른 프로젝트에 그대로 적용이 가능
- 앱의 비즈니스 로직에 사용되는 **Model**

**왜 Data, Doamin을 나누는가? Data Entity와 Domain Model의 차이는?**
---

- 둘을 구분하지 않고 하나로 사용할때 **Server**, **DB**등의 스펙이 바뀐다면 변경해야할 부분이 많아질것
- 클린 아케텍처에 의하면 **Domain**계층에서는 프레임워크에 의존하지 않는 순수 **Java**/**Kotlin** 코드로 작성되어야함.
**Data**계층의 **Entity**는 **Server**, **DB**에서 데이터를 불러오기 위한 의존성이 추가될 수 있기에 분리
- 둘의 형태가 유사할 수 있지만, 이는 진짜 중복이 아닌 서로 다른 이유와 속도로 변경될 가능성이 높은 우발적 중복이기 때문
    - **Data Entity**는 **Server** ,**DB**의 스펙 변경
    - **Domain Entity**는 비즈니스 로직의 변경

**우발적 중복과 진짜 중복**
---

- 진짜 중복
    - 한 인스턴스가 변경되면, 동일한 변경을 그 인스턴스의 모든 복사본에 반드시 적용해야 한다
- 우발적 중복(거짓된 중복)
    - 중복으로 보이는 두 코드의 영역이 각자의 경로로 발전한다면, 즉 **서로 다른 속도와 다른 이유로 변경**된다면 이 두 코드는 진짜 중복이 아니다
    - 사실 별개의 로직이었어야 하는데 우연히 내용이 같을 뿐, 이후 **다른 방향으로 변경될 가능성이 높은 코드**
    - **SOLID**의 **SSP**(단일 책임 원칙)에 위반되지 않도록 하기 위한 중복. 이라고 칭할 수 있을것 같음
