### ISSUE TITLE
[Refactor] String Resource를 사용한 문자열 처리

### ISSUE THREAD

**Issue by wjchoi96** [wjchoi96/KakaoGallery#41]
### String Resource를 사용한 문자열 처리
- #42 
## 📚 To-do

- [x] StringResourceProvider 타입 생성
- [x] ViewModel에서 ResourceProvider를 주입받아, string resource로부터 문자열을 제공받아 처리
- [x] SearchViewModel에 ResourceProvider 적용
- [x] SearchFragment에 하드코딩 텍스트를 string resource로 대체
- [x] GalleryViewModel에 ResourceProvider 적용
- [x] GalleryFragment에 하드코딩 텍스트를 string resource로 대체

**Comment by wjchoi96** [comment]
**Android에서 String Resouce를 사용해서 문자열을 처리해야 하는 이유**
---

- 애플리케이션 수정 없이 리소스를 수정할 수 있음
- 앱의 다른 부분에서 문자열을 더 쉽게 재사용 할 수 있음
- 다국어 지원에 용이

**ViewModel에서 context를 알아서 안되는 이유**
---

- **ViewModel**은 **Activity**, **Fragment**보다 생명주기가 길기 때문에 해당 **context**를 **viewModel**이 참조해서는 안됨
    - **Activity**, **Fragment**가 **Destroy**된 이후에 잘못된 **context**에 접근하여 문제 발생 가능
    - 해당 **context**를 참조하는 클래스를 참조해서도 안됨
- 테스트를 쉽게 하기 위해서는 **ViewModel**에 특정 **Android**코드가 포함되어서는 안됨
    - **Application**을 참조하고 있는 **AndroidViewModel**이 존재하는 이유는?
        - 위에서 언급했듯이 **ViewModel**은 **Activity**, **Fragment**의 **context**를 참조해서는 안된다. 그에 대한 해결방안으로 제시된 방법 중 하나이지만, 사용한다면 테스트가 어려워질것
    - **testable**한 코드를 작성하고자 한다면 **정말 타당한 이유가 없는한 context를 ViewModel에서 사용하지 말것을 권장**
- **Clean Architecture**에서 **ViewModel**은 **Interface Adapter(Presenter)**에 속함. 따라서 특정 플랫폼과 관계가 없어야 함
    - **Interface Adapter(Presenter)**
        - 상위계층인 `UseCase`, 프레임워크와 같은 하위 계층간의 중간다리 역할
        - 데이터를 `Entity`및 `UseCase`의 편리한 형식에서 데이터베이스 및 웹에 적용 할 수 있는 형식으로 변환
        - `MVP의 Presenter`, `MVVM의 ViewModel` 및 `Gateway(Repository)`가 포함된다
        - 순수한 비즈니스 로직만을 담당하는 역할

**그렇다면 ViewModel에서 String Resource를 어떻게 처리해야 하는가?**
---

- **ViewModel**이 아닌, **View**에서 처리하는 방법
    - **ViewModel**에서 **Exception**이나 따로 정의한 **enum class**를 전달하고, **View**에서 전달된 값에 따라 특정 **string resouce**를 불러오는 방식
    - 특정 타입을 **string resource id**로 매칭하는 코드가 필요
- **ResourceProvider** 클래스를 생성하여 필요한 리소스(문자열)을 제공받는 방법
    - 이것또한 **string resource id**와 매칭되는 **enum class** 정의가 필요
- **ViewModel**을 확장하여 **Application**을 참조하고 있는 **AndroidViewModel** 사용
    - 특정 플랫폼에 포함되는 코드를 가지게 되므로, 치명적인 문제는 없지만 가능하다면 사용하지 않는게 좋을것 같음
- **ViewModel**에 **R**을 **import**하여 **resouce** **id**를 **view**에 전달하는 방법

**결론**
---

- **View**에서 처리하거나, **ResourceProvider**를 생성하여 문자열을 제공받는 방법이 좋아보인다
    - 다만, 둘 모두 특정 타입을 **string resource id**와 매칭하는 코드가 추가되어야 함
