### ISSUE TITLE
[Refactor] MVVM 아키텍처에 걸맞게 관심사 분리 

### ISSUE THREAD

**Issue by wjchoi96** [wjchoi96/KakaoGallery#42]
## 📚 To-do

- [x] [Refactor] String Resource를 사용한 문자열 처리
- [x] UiEvent 적용
- [x] SearchImage Fragment, ViewModel 점검, 수정
- [x] Gallery Fragment, ViewModel 점검, 수정
- [x] Gallery 화면 DataBinding 적용
- [x] Search 화면 DataBinding 적용
