### ISSUE TITLE
[Refactor] Rx Observable 코드 리팩토링

### ISSUE THREAD

**Issue by wjchoi96** [wjchoi96/KakaoGallery#44]
### 

## 📚 To-do

- [x] Observable 생성 연산자 올바르게 적용(just vs callable)
- [x] Observable을 생성하는 위치 고민및 적용
- [x] Observable 대신 Completable, Single 등을 사용 고려
- [x] Observable vs Flowable
- [x] Single을 리턴하는 UseCase는 결과를 래핑할 래퍼클래스를 제거

**Comment by wjchoi96** [comment]
## 내부 코드를 통해 확인된 just와  create와의 차이점

**just**
---
- `just(item: T)`는 연산이 아닌 값을 취급
전달된 **item**을 가지는 **ObservableJust**를 **즉시 생성**
즉, 전달되는 **item**이 **heavy logic** 이후 리턴되는 결과값이라면, 해당 **item**을 얻어내는 **heavy logic**은 `just()`가 호출된 쓰레드에서 동작하게 됨
- **ObservableJust**의 `subscribeActual(observer: Observer`)에서 
멤버로 가진 item과 전달된 observer를 멤버로 하는 **ScalarDisposable**를 생성
**ScalarDisposable**를 전달인자로 하여 `observer.subscribe`를 호출. 즉, **observer**가 **ScalarDisposable**를 바라봄
- 이후 **ScalarDisposable.run()**을 호출하여 내부적으로 **onNext**, **onComplete**를 호출하도록 함
- **just**는 **item**의 생성에는 관여하지 않으며
**observer**가 **subscribe**를 호출하면, 전달된 **item**을 내부적으로 **observer**에게 전달되도록 **onNext**, **onComplete**를 호출함

**create**
---

- **create** 람다식은 **ObservableOnSubscribe**의 `subscribe(emitter: ObservableEmitter)`를 의미
- **ObservableOnSubscrib를 멤버로 가지는 ObservableCreate**를 즉시 생성
- **ObservableCreate**의 `subscribeActual(observer: Observer`)에서 
멤버로 가진 `ObservableOnSubscribe.subscribe`를 호출
즉, **subscribeActual**이 호출되어야, **create** 람다식이 실행됨

**Comment by wjchoi96** [comment]
## 내부 코드를 통해 확인된 just와  create와의 차이점

**just**
---
- `just(item: T)`는 연산이 아닌 값을 취급
전달된 **item**을 가지는 **ObservableJust**를 **즉시 생성**
즉, 전달되는 **item**이 **heavy logic** 이후 리턴되는 결과값이라면, 해당 **item**을 얻어내는 **heavy logic**은 `just()`가 호출된 쓰레드에서 동작하게 됨
- **ObservableJust**의 `subscribeActual(observer: Observer`)에서 
멤버로 가진 item과 전달된 observer를 멤버로 하는 **ScalarDisposable**를 생성
**ScalarDisposable**를 전달인자로 하여 `observer.subscribe`를 호출. 즉, **observer**가 **ScalarDisposable**를 바라봄
- 이후 `ScalarDisposable.run()`을 호출하여 내부적으로 **onNext**, **onComplete**를 호출하도록 함
- **just**는 **item**의 생성에는 관여하지 않으며
**observer**가 **subscribe**를 호출하면, 전달된 **item**을 내부적으로 **observer**에게 전달되도록 **onNext**, **onComplete**를 호출함

**create**
---

- **create** 람다식은 **ObservableOnSubscribe**의 `subscribe(emitter: ObservableEmitter)`를 의미
- **ObservableOnSubscrib를 멤버로 가지는 ObservableCreate**를 즉시 생성
- **ObservableCreate**의 `subscribeActual(observer: Observer`)에서 
멤버로 가진 `ObservableOnSubscribe.subscribe`를 호출
즉, **subscribeActual**이 호출되어야, **create** 람다식이 실행됨


**단순한 값을 전달하는 용도가 아닌, 어떤 연산 이후 결과를 전달하는 용도로는 just를 사용하면 문제가 생길 수 있음**

**Comment by wjchoi96** [comment]
## 내부코드를 통해 확인되는 defer과 fromCallable의 차이
**defer**
---

- `defer{ }`람다식을 통해 **Supplier**의 `get()`메소드를 구현
    - 이때 **Supplier**의 제네릭 타입은 **ObservableSource**의 자식이여야 함
- 전달된 람다식(**Suplier**)는 **ObservableDefer**로 래핑됨
- **ObservableDefer**는 **Observable**을 상속받았기에 **subscribeActual**을 구현
    - **subscribeActual**함수에서 `Supplier.get()`을 호출하여, `defer{ }`람다식을 실행시킴
    즉, 이때 `defer{ }`람다식에서 생성한 **Observable**이 생성되는것
    - **subscribeActual**의 매개변수로 전달된 **Observer**을 매개변수로 하여, `Supplier.get()`을 통해 얻어온 `Observable.subscribe`를 수행
- **Observable**을 생성하기 위한 **Observable**을 생성
`ObservableDefer`, `defer{ }`람다식에서 생성하는 **Observable 총 2개**
- 생성할 **Observable**을 구독(subscribe)가 이루어져야 생성되는 지연생성(lazy initialize)하는게 주 기능이라고 판단됨

**fromCallable**
---

- `fromCallable{ }`람다식을 통해 **Callable**의 `call()`메소드를 구현
- 전달된 람다식(**Callable**)은 **ObservableFromCallable**로 래핑됨
- **ObservableFromCallable**은 **Observable**을 상속받았기에 **subscribeActual**을 구현
    - **subscribeActual**함수의 매개변수로 전달된 **Observer**가 **DeferredScalarDisposable**객체로 래핑됨
    - **Observer**를 수신자로, **DeferredScalarDisposable**를 매개변수로 **onSubscribe**메소드 호출
    - **subscribeActual**함수에서 `Callable.call()`을 호출하여, `fromCallable{ }`람다식을 실행시켜 `call()`메소드 수행 결과를 얻음
    해당 데이터를 매개변수로 하여 **DeferredScalarDisposeable**의 **complete** 호출
- **단일 데이터만을 처리 가능함**
- 구독(subscribe)이 이루어질때 연산을 수행하고, 그 결과를 **Observable**로 생성하는게 주 기능이라고 판단됨.
이것 또한 지연생성(Lazy initialize)라고 판단됨

**defer vs fromCallable**
---

- 둘다 구독(subscribe)가 이루어져야 **Observable**을 생성하는 지연 생성(lazy initialize)방식
- **defer**은 **Observable**생성을 위해 **Observable**을 생성하는 구조이기에, 꼭 필요한 경우가 아니라면 **fromCallable**을 사용하는게 좋아 보임
- **fromCallable**은 단일 데이터만을 처리 가능하기에, 여러 데이터를 **stream**형태로 처리할것이라면 **defer**를 사용
- 수행하려는 연산 결과가 **Observable**이라면, 굳이 **subscribe**를 호출해 얻은 데이터를 **fromCallable**로 호출하기보다, **defer**를 사용하는게 좋아 보임

**Comment by wjchoi96** [comment]
## 어느 모듈에서 Observable을 생성해야 할까?

**우선 RxJava를 도입한 이유?**
---
- 콜백 구조의 해결
- 안전하고 간결한 비동기 처리 코드를 쉽게 작성
    - 동시성, 데드락 등의 문제를 **RxJava** 내부적으로 지원
- 반응형 프로그래밍 패러다임 적용
    - 선언적 프로그래밍
    - 변화의 전파와 데이터 흐름
        - 데이터에 변화가 일어나면 이벤트를 발생시켜 데이터를 통지

**라이브러리들은 Observable을 어떻게 사용하지?**
----

- **Room**의 **Dao**, **Retrofit**의 **Service**모두 **Observable**, **Flowable**, **Flow등의** 형태를 리턴하는 함수를 지원하고 **단순 데이터** 형태로 리턴하는 함수도 지원
    - **필요하다면 어떠한 형태로도 리턴 가능**
    - **필요하지 않다면 굳이 Observable을 사용할 필요 없음**

 **그렇다면 Observable을 생성하는 위치는?**
---
- 지속적인 데이터의 흐름이 필요하다면 **Observable** 생성
- 비동기 처리가 필요한 부분에서 **Observable**을 생성
- 비동기 처리도 필요하지 않고, 지속적인 데이터 흐름도 필요하지 않다면 **Observable**로 데이터를 래핑할 필요가 없음
- 의존 모듈에서 **Observable**을 리턴한다면 실제 **observer(UI)**에 도착하기 전에 **subscribe**를 **호출하지 않고** 지원되는 **operator**를 사용하여 **데이터 가공, Scheduler 변경을 수행**
    - 실제 **observer**(ui)가 아닌데 **subscribe**를 수행한다면 **observer**(ui)가 **dispose**하여도, 해당 모듈에서는 데이터의 흐름이 발생할 수 있기 때문
    - 다만, 꼭 필요한 경우가 있다면 **subscribe** 수행 가능
    이 경우, 따로 **dispose** 처리를 고민해야 할것

**Comment by wjchoi96** [comment]
**Observable** vs **Single**, **Completable**
---

- 하나의 데이터를 통지하는 경우 **Single**을 권장
- 이벤트의 완료만을 통지하는 경우 **Completeable**을 권장
- 하지만, 확장성을 고려하여 도입하지 않고 **Observable**로 통일하기로 결졍
    - **Single**, **Completable**은 **Observable**이 변형된, 별개의 타입이기 때문

**Comment by wjchoi96** [comment]
**Single을 리턴하는 UseCase는 결과를 래핑할 래퍼클래스를 제거**
---

- **Observable**의 경우 **onError**로 예외상황, 작업 실패를 알릴 경우 **Stream**이 종료됨
때문에, **Presentation**과 **Domain**의 접점인 **UseCase**에서 작업 결과를 **Result**를 사용해서 래핑
- **Single**의 경우 하나의 **data** 혹은 **error**를 통지하기때문에 **onError**로 예외상황, 작업 실패를 알려도 무방
