### ISSUE TITLE
[Test] Data, Domain 레이어 테스트 코드 작성

### ISSUE THREAD

**Issue by wjchoi96** [wjchoi96/KakaoGallery#57]
### Data, Domain 레이어 테스트 코드 작성
- 테스트 코드는 설계도의 역할도 수행하도록 작성
- 해당 브랜치가 머지된 이후의 테스트 코드는 feature, refactor, modify 브랜치에서 관련 테스트 코드의 작성, 수정을 포함하게 될 것
## 📚 To-do

- [x] Dao 테스트 코드 작성
- [x] DataSource 테스트 코드 작성
- [x] Repository 테스트 코드 작성
- [x] UseCase 테스트 코드 작성

**Comment by wjchoi96** [comment]
### 테스트 더블이란?

- [[xUnit Test Patterns](http://www.acornpub.co.kr/book/xunit)](http://www.acornpub.co.kr/book/xunit)의 저자인 제라드 메스자로스(Gerard Meszaros)가 만든 용어

> When we are writing a test in which we cannot (or chose not to) use a real depended-on component (DOC), we can replace it with a Test Double.
> 
> 
> The Test Double doesn’t have to behave exactly like the real DOC; it merely has to provide the same API as the real one so that the SUT thinks it is the real one!
> 

> 테스트 코드를 작성할 때 실제 DOC(depoended-on component; 의존 구성 요소)를 사용할 수 없다면, DOC 대신 테스트 더블로 대체할 수 있음.
> 
> 
> 테스트 더블은 실제 DOC와 똑같이 행동하지 않아도 되며, 똑같은 API만 제공하면 된다.
> 
- **테스트 더블은 의존 구성요소를 사용할 수 없을때, 테스트 대상 코드와 상호작용 하는 객체**

### 테스트 더블 종류

- **Dummy**
    - 가장 기본적인 테스트 더블
    - 해당 객체의 기능까지는 필요하지 않고, 인스턴스화 된 객체만이 필요할때 사용
    - **Dummy**객체의 메소드의 정상 동작은 보장하지 않음
    - **구현을 제외한 인터페이스 or 기본 클래스의 파생 객체**
    - 객체는 전달되지만 사용되지 않는 객체
- **Stub**
    - **Dummy**객체가 실제로 동작하는 것처럼 보이게 만들어 놓은 객체(최소한의 구현)
    - 호출자를 실제 구현물로부터 격리시키는 목적으로 사용
    - **인터페이스 or 기본 클래스가 최소한으로 구현된 상태**
    - 테스트에서 호출된 요청에 대해 미리 준비해둔 결과를 제공
- **Fake**
    - 복잡한 로직이나 객체 내부에서 필요로 하는 다른 외부 객체들의 동작을 단순화하여 구현한 객체
    - **동작의 구현을 가지고 있지만, 실제 프로덕션에는 적합하지 않은 객체**
- **Spy**
    - 테스트에서 특정 객체가 사용되었는지, 특정 메소드가 정상적으로 호출되었는지 확인해야 하는 상황에 사용
    - **Stub**의 역할을 가지면서 호출된 내용에 대해 약간의 정보를 기록
        - 테스트에서 확인하기 위한 정보
- **Mock**
    - **호출에 대한 기대를 명세하고 내용에 따라 동작하도록 프로그래밍된 객체**
    - 테스트 작성을 위한 환경 구축이 어려울때 사용
        - 환경 구축을 위한 작업 시간이 많이 필요한 경우 Mock객체를 사용
        - 특정 모듈을 아직 보유하고 있지 않아서 테스트 환경을 구축하지 못할 경우
        - **Retrofit**을 **Mock**객체로 대체해본 경험을 해봄
    - 테스트가 특정 경우나 순간에 의존적일 때 사용
    - 테스트 시간이 오래걸리는 경우 사용

### 상태 기반 테스트 vs 행위 기반 테스트



- 상태 기반 테스트(**state base test**)
    - 특정한 메소드를 거친 후, 객체의 상태에 대해 예상값과 비교하는 방식
    - `setName()`메소드를 호출했다면, `getName()`메소드로 확인해보는 방식
- 행위 기반 테스트(**behavior base test**)
    - 올바른 로직 수행에 대한 판단의 근거로 특정한 동작의 수행 여부를 이용
    - 메소드의 리턴값이 없거나, 리턴값을 확인하는 것만으로는 예상대로 동작했음을 보증하기 어려운 경우
    - **Spy**객체를 사용하거나, **Mock**객체를 테스트를 진행
    - 행위를 점검하는것으로 테스트 케이스를 만드는 방식

### Test Double Mock vs Mock Object



- 일반적인 테스트 더블은 상태 기반 테스트 케이스를 작성
- Mock객체는 행위 기반 테스트 케이스를 작성
