### ISSUE TITLE
[Refactor] Repository 패턴 적용

### ISSUE THREAD

**Issue by wjchoi96** [wjchoi96/KakaoGallery#6]
### Repository 패턴 적용
- #1 

## 📚 To-do

- [x]  ApiService를 사용하는 RemoteDataSource 추가
- [x]  Change Storage to Local DataSource
- [x]  DataSource는 ApiService, Dao로부터 데이터 요청
- [x]  Repository는 DataSource의 요청 결과를 Domain Model로 가공
- [x]  Repository, DataSource 추상화하여 각 모듈간 인터페이스 타입에 의존하도록 변경

**Comment by wjchoi96** [comment]
**해결하려는 문제**


- **Retrofit**을 통해 **Api**통신을 진행할때 `subscribeOn()`연산자를 사용해 **IO** **Scheduler**에서 작업을 수행하려 하는데, 적용이 안되는 문제

**원인**


- **Retrofit RxJavaAdpater**을 사용하여 **flowable**, **observable** 등 스트림 형태의 데이터를 리턴하는 경우 발생
- **Retrofit** 의 **RxSupport** 기능에서 `subscribeOn()`을 통해 지정한 스케쥴러는 네트워크 호출을 준비하기 위한 코드에만 적용이되고 실제 네트워크 호출 코드는 **Rx** 에서 지정한 스케쥴러가 적용이 된다. 
때문에, 해당 스케쥴러로 다운스트림이 실행되는 것

**해결**

- **Retrofit** **RxJavaAdpater**에서 제공하는 기능인 만큼 의미없는 `subscribeOn()`을 통해 **Scheduler** 변환을 하지 않도록 함
