### ISSUE TITLE
[Fix] 이미지 선택 도중 다른 query검색 시, 이전 이미지 선택 정보가 남아있는 문제

### ISSUE THREAD

**Issue by wjchoi96** [wjchoi96/KakaoGallery#77]
## 📚 To-do

- [x]  새로운 query를 검색한다면, 기존 선택된 이미지 초기화
- [x]  같은 query를 검색한다면, 기존 선택된 이미지 유지
- [x]  같은 query를 검색할때, 1페이지가 아닌 페이지에 선택된 이미지가 존재한다면, 해당 선택된 이미지는 초기화 처리
