### ISSUE TITLE
[Feature] 에러 메세지 표시를 스낵바로 표시

### ISSUE THREAD

**Issue by wjchoi96** [wjchoi96/KakaoGallery#94]
## 📚 To-do

- [ ] 메시지만 보여주는 스낵바 적용
- [ ] 버튼이 필요하다면 버튼이 추가된 스낵바 적용(재시도 처리 등)
- [ ] 재시도 로직 구현(retry)

## 🕐 목표 작업 시간

11.27 18:00 - 19:00
11.27 20:30 - 22:30

**Comment by wjchoi96** [comment]
Issue 범위를 헷갈려서 #100 이슈에 통합해서 진행함
- #100
